apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: my-external-secret
spec:
  backendType: secretsManager
  data:
    - key: my-secret-key
      name: my-target-secret
      property: my-property-key
---
apiVersion: v1
kind: Secret
metadata:
  name: my-app-secret
data:
  my-app-key: $(my-target-secret:my-property-key)
