# vim configmap.yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfig
data:
  config.txt: |
    Avatar: Killu
    Game: Valorant
    Rank: Immortal
# kubectl apply -f configmap.yml
---
# vim deploy.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: httpd
        ports:
        - containerPort: 80
        volumeMounts:
          - name: keyconfig
            mountPath: /script
      volumes: 
        - name: keyconfig
          configMap:
            name: myconfig
# kubectl apply -f deploy.yml
---
# vim confsvc.yml
apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
  - port: 80
    targetPort: 80
# kubectl apply -f confsvc.yml
# kubectl get configmaps
# kubectl get deployment
# kubectl get pod
# kubectl get svc
# kubectl exec -it <POD-NAME> bash
#     ls /script
#     grep "Avatar:" /script/config.txt | cut -d ":" -f 2 > /usr/local/apache2/htdocs/index.html
# (HIT IP ON BROWSER)
# kubectl edit configmaps <CONFIGMAP-NAME> 
# kubectl rollout restart deployment <DEPLOYMENT-NAME>
# kubectl get pod
# kubectl exec -it <POD-NAME> bash
#     grep "Avatar:" /script/config.txt | cut -d ":" -f 2 > /usr/local/apache2/htdocs/index.html
# (HIT IP ON BROWSER)

