apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  strategy:
    type: Recreate 
  template: 
    metadata: 
      labels: 
        app: myapp
    spec: 
      containers:
        - name: myapp
          image: mariadb
          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-db-secret
                  key: db-secret-pass
          ports:
            - name: myapp
              containerPort: 3306
          volumeMounts:
            - name: persistent-storage
              mountPath: /var/lib/maria    
            - name: dbcreation-script
              mountPath: /docker-entrypoint-initdb.d 
      volumes: 
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: ebs-pv-claim
        - name: dbcreation-script
          configMap:
            name: dbcreation-script

# kubectl exec -it myapp-55c47fdbc4-6j8d9 -c myapp -- /bin/bash
# mysql -u root -h localhost -pdbpassword11
# show databases;
# use studentapp;
# show tables;
