apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-pv-claim
  # namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources: 
    requests:
      storage: 4Gi